CONTRACTS = {
    "ropsten": {
        "bokky_token_factory":"",
        "miso_token_factory":"",
        "mintable_token_template":"",
        "mintable_token":"",
        "dutch_auction_template":"",
        "auction_house":"",
        "dutch_auction":"",
        "gnosis_safe":"",
        "proxy_factory":"",
        "gnosis_vault":""
    },
    "mainnet":{
        "bokky_token_factory":"",
        "miso_token_factory":"",
        "mintable_token_template":"",
        "mintable_token":"",
        "dutch_auction_template":"",
        "auction_house":"",
        "dutch_auction":"",
        "gnosis_safe":"",
        "proxy_factory":"",
        "gnosis_vault":""
    },
    "rinkeby": {
        "bokky_token_factory":"",
        "miso_token_factory":"",
        "mintable_token_template":"",
        "mintable_token":"",
        "dutch_auction_template":"",
        "auction_house":"",
        "dutch_auction":"",
        "gnosis_safe":"0x6851D6fDFAfD08c0295C392436245E5bc78B0185",
        "proxy_factory":"0x76E2cFc1F5Fa8F6a5b3fC4c8F4788F0116861F9B",
        "gnosis_vault":"0xb50c0AE9E50c31d2DA2a82E92dF3c8BC6f8F5C7e"
    },
    "kovan": {
        "bokky_token_factory":"",
        "miso_token_factory":"",
        "mintable_token_template":"",
        "mintable_token":"",
        "dutch_auction_template":"",
        "auction_house":"",
        "dutch_auction":"",
        "gnosis_vault":""
    },
    "goerli": {
        "bokky_token_factory":"",
        "miso_token_factory":"",
        "mintable_token_template":"",
        "mintable_token":"",
        "dutch_auction_template":"",
        "auction_house":"",
        "dutch_auction":"",
        "gnosis_vault":""
    },
    "development": {
        "bokky_token_factory":"",
        "miso_token_factory":"",
        "mintable_token_template":"",
        "mintable_token":"",
        "dutch_auction_template":"",
        "auction_house":"",
        "dutch_auction":"",
        "gnosis_safe":"",
        "proxy_factory":"",
        "gnosis_vault":""
    }
}